name: 'Security Vulnerability Scan'
description: 'Composite action to scan for vulnerable NuGet packages'

outputs:
  vulnerable:
    description: 'Whether vulnerable packages were detected (true/false)'
    value: ${{ steps.scan.outputs.vulnerable }}
  scan-file:
    description: 'Path to security scan results file'
    value: 'security-scan.txt'

runs:
  using: 'composite'
  steps:
    - name: Run vulnerability scan
      id: scan
      shell: bash
      run: |
        echo "ðŸ” Scanning for vulnerable packages..."
        dotnet list package --vulnerable --include-transitive 2>&1 | tee security-scan.txt
        
        if grep -q "has the following vulnerable packages" security-scan.txt; then
          echo "vulnerable=true" >> $GITHUB_OUTPUT
          echo "::warning::âš ï¸ Vulnerable packages detected - review security-scan.txt"
          cat security-scan.txt
        else
          echo "vulnerable=false" >> $GITHUB_OUTPUT
          echo "âœ… No vulnerable packages detected"
        fi
