name: 'Setup .NET Environment'
description: 'Composite action to setup .NET SDK and display version'

inputs:
  dotnet-version:
    description: '.NET SDK version to install'
    required: false
    default: '8.0.x'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Display .NET version
      shell: bash
      run: |
        echo "### .NET SDK Information" >> $GITHUB_STEP_SUMMARY
        dotnet --version
        dotnet --info | head -n 10
